name: Publish to nuget

on:
  workflow_call:
    secrets:
      nuget_key:
        required: true
        description: Key to Nuget Repository
    inputs:
      package_name:
        type: string
        required: true
      package_folder:
        type: string
        default: .
      package_path:
        type: string
      version:
        type: string
        default: ${{github.ref_name}}
      nuget_repo:
        type: string
        default: https://api.nuget.org/v3/index.json

jobs:
  publish:
    name: Publish build
    runs-on: windows-latest
    steps:
      ## SETUP ##
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          dotnet-version: 9.x
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      ## BUILD ##
      - name: Restore
        working-directory: ${{inputs.package_folder}}
        run: msbuild -t:restore
      - name: Build for version [${{inputs.version}}] 
        working-directory: ${{inputs.package_folder}}
        run: msbuild -t:clean,build -p:Configuration=Release -p:AssemblyVersion=${{inputs.version}}
      ## NUGET PUBLISH ##
      - name: Package
        working-directory: ${{inputs.package_folder}}
        run: msbuild -t:pack -p:Configuration=Release -p:AssemblyVersion=${{inputs.version}}
      - name: Publish
        working-directory: ${{inputs.package_folder}}
        run: | 
          $packagePath = "${{ inputs.package_path }}"
          if (-not $packagePath) {
            $packagePath = "BUILD/NuGet/${{ inputs.package_name }}.${{ inputs.version }}"
            echo "No package path specified, using '${packagePath}' as default"
          }
          dotnet nuget push "${packagePath}.nupkg" --api-key ${{ secrets.nuget_key }} --source ${{ inputs.nuget_repo }}
